### ISSUE TITLE
oauth-authorization-server doesn't start as fat-jar

### ISSUE THREAD

**Issue by TomaszBelina** [Baeldung/spring-security-oauth#188]
$ mvn clean package
$ java -jar /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar target/oauth-authorization-server-0.1.0-SNAPSHOT.jar

application starts but is not usable. Log file contains:

java.nio.file.NoSuchFileException: /home/user/Projects/spring-security-oauth/oauth-rest/oauth-authorization-server/target/oauth-authorization-server-0.1.0-SNAPSHOT.jar!/BOOT-INF/lib/keycloak-model-jpa-8.0.0.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[na:na]
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[na:na]
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763) ~[na:na]
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225) ~[na:na]
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727) ~[na:na]
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844) ~[na:na]

**Comment by sampada07** [comment]
Hi @TomaszBelina - couple of things here. 
1. oauth-authorization-server in this repository is using JDK 13. Could you please try with it instead of 11?
2. When the application starts, navigate to _http://localhost:8083/auth_ to use keycloak.  http://localhost:8083/ is not mapped to anything.

**Comment by TomaszBelina** [comment]
I've used JDK 13 and issue is exactly the same.
java.nio.file.NoSuchFileException: /tmp/spring-security-oauth/oauth-rest/oauth-authorization-server/target/oauth-authorization-server-0.1.0-SNAPSHOT.jar!/BOOT-INF/lib/keycloak-model-jpa-8.0.0.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[na:na]
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[na:na]
        at java.base/java.nio.file.Files.readAttributes(Files.java:1842) ~[na:na]
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1160) ~[na:na]
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719) ~[na:na]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239) ~[na:na]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:256) ~[na:na]
        at org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.resolveJarFileReference(JarFileBasedArchiveDescriptor.java:168) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.visitArchive(JarFileBasedArchiveDescriptor.java:51) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:47) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:76) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:98) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:242) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:175) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:76) ~[hibernate-core-5.4.9.Final.jar!/:5.4.9.Final]
        at org.keycloak.connections.jpa.util.JpaUtils.createEntityManagerFactory(JpaUtils.java:60) ~[keycloak-model-jpa-8.0.0.jar!/:8.0.0]

**Comment by sampada07** [comment]
Hi @TomaszBelina ,

While i open an internal ticket to look at the issue you reported further, can you please try the second point i mentioned earlier?

Despite the error, the deployment is successful and we can log in to the admin console - http://localhost:8083/auth/admin - with credentials as defined in the projects application.yml 

Cheers!

**Comment by sampada07** [comment]
Hi @TomaszBelina, 

We've fixed the issue, thanks for bringing it to our notice.

Cheers!
