### ISSUE TITLE
NullPointerException using keycloak 12.0.4

### ISSUE THREAD

**Issue by hbrackmann** [Baeldung/spring-security-oauth#239]
using keycloak  12.0.4 I get the exception: (works with 11.0.2)
```
java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RoleProvider.getRoleById(org.keycloak.models.RealmModel, String)" because the return value of "org.keycloak.models.KeycloakSession.roleLocalStorage()" is null
	at org.keycloak.storage.RoleStorageManager.getRoleById(RoleStorageManager.java:140)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRoleById(RealmCacheSession.java:805)
	at org.keycloak.models.jpa.RealmAdapter.getRoleById(RealmAdapter.java:897)
	at org.keycloak.models.jpa.RealmAdapter.getRoleNameById(RealmAdapter.java:715)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:254)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:412)
	at org.keycloak.services.managers.ApplianceBootstrap.isNewInstall(ApplianceBootstrap.java:46)
	at org.keycloak.services.resources.KeycloakApplication.migrateAndBootstrap(KeycloakApplication.java:200)
	at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:138)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:228)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:129)

**Comment by Ranger-118** [comment]
Same error found, will this repo update along with the new Keycloak version?

**Comment by kwoyke** [comment]
As for now we run on 11.0.2. But of course, we should update the version in the future.
