### ISSUE TITLE
TypeError: Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by azizkhani** [Baeldung/spring-security-oauth#52]
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:226:132)
    at new ObjectSchemaTreeNode (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
    at Array.map (<anonymous>)
    at OneOfSchemaTreeNode (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (/Users/aliakbarazizkhani/git/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oauth-implicit@0.0.0 start: `ng serve --port 8086`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oauth-implicit@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aliakbarazizkhani/.npm/_logs/2017-11-11T20_07_37_470Z-debug.log

**Comment by eugenp** [comment]
Hey @azizkhani - someone from the team tried to reproduce this one and everything worked fine for her. So, I'm curious if you're still running into it, or if you figured out what the problem was. 

Cheers, 
Eugen.

**Comment by eugenp** [comment]
Hey @azizkhani - I haven't seen any update from you here, so I'm closing this one. 
Cheers, 
Eugen.
