### ISSUE TITLE
cant access to employee

### ISSUE THREAD

**Issue by sofior** [Baeldung/spring-security-oauth#92]
I can use token to access resource server 1&2 but can't access to security oauth server's employee(GET).
something wrong with me?

2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.b.w.s.f.OrderedRequestContextFilter  : Bound request context to thread: org.apache.catalina.connector.RequestFacade@781292c9
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/oauth/token']
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/oauth/token'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/oauth/token_key']
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/oauth/token_key'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/oauth/check_token']
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/oauth/check_token'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 1 of 12 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 2 of 12 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] w.c.HttpSessionSecurityContextRepository : No HttpSession currently exists
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: null. A new one will be created.
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 3 of 12 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 4 of 12 in additional filter chain; firing Filter: 'LogoutFilter'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', GET]
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/logout'
2018-06-21 23:32:20.637 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', POST]
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /employee' doesn't match 'POST /logout
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', PUT]
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /employee' doesn't match 'PUT /logout
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /employee' doesn't match 'DELETE /logout
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 5 of 12 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /employee' doesn't match 'POST /login
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 6 of 12 in additional filter chain; firing Filter: 'DefaultLoginPageGeneratingFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 7 of 12 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 8 of 12 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 9 of 12 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.a.AnonymousAuthenticationFilter  : Populated SecurityContextHolder with anonymous token: 'org.springframework.security.authentication.AnonymousAuthenticationToken@495884c5: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 10 of 12 in additional filter chain; firing Filter: 'SessionManagementFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 11 of 12 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.security.web.FilterChainProxy        : /employee?email=123 at position 12 of 12 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/login'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/oauth/token/revokeById/**'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/tokens/**'
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /employee?email=123; Attributes: [authenticated]
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@495884c5: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
2018-06-21 23:32:20.639 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@ae3fdf8, returned: -1
2018-06-21 23:32:20.640 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84) ~[spring-security-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233) ~[spring-security-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:124) ~[spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:206) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.baeldung.config.CorsFilter.doFilter(CorsFilter.java:32) [classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.util.matcher.AndRequestMatcher   : Trying to match using NegatedRequestMatcher [requestMatcher=Ant [pattern='/**/favicon.ico']]
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/employee'; against '/**/favicon.ico'
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.NegatedRequestMatcher  : matches = true
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.util.matcher.AndRequestMatcher   : Trying to match using NegatedRequestMatcher [requestMatcher=MediaTypeRequestMatcher [contentNegotiationStrategy=org.springframework.web.accept.ContentNegotiationManager@76fe3b10, matchingMediaTypes=[application/json], useEquals=false, ignoredMediaTypes=[*/*]]]
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.m.MediaTypeRequestMatcher      : httpRequestMediaTypes=[application/json, text/plain, */*]
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.m.MediaTypeRequestMatcher      : Processing application/json
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.m.MediaTypeRequestMatcher      : application/json .isCompatibleWith application/json = true
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.u.matcher.NegatedRequestMatcher  : matches = false
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.util.matcher.AndRequestMatcher   : Did not match
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.s.HttpSessionRequestCache        : Request not saved as configured RequestMatcher did not match
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.a.ExceptionTranslationFilter     : Calling Authentication entry point.
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.web.DefaultRedirectStrategy        : Redirecting to 'http://localhost:8081/spring-security-oauth-server/login'
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@7db47ef0
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2018-06-21 23:32:20.641 DEBUG 14560 --- [nio-8081-exec-4] o.s.b.w.s.f.OrderedRequestContextFilter  : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@781292c9
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.b.w.s.f.OrderedRequestContextFilter  : Bound request context to thread: org.apache.catalina.connector.RequestFacade@781292c9
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/oauth/token']
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login'; against '/oauth/token'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/oauth/token_key']
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login'; against '/oauth/token_key'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/oauth/check_token']
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login'; against '/oauth/check_token'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.security.web.FilterChainProxy        : /login at position 1 of 12 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.security.web.FilterChainProxy        : /login at position 2 of 12 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] w.c.HttpSessionSecurityContextRepository : No HttpSession currently exists
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: null. A new one will be created.
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.security.web.FilterChainProxy        : /login at position 3 of 12 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.security.web.FilterChainProxy        : /login at position 4 of 12 in additional filter chain; firing Filter: 'LogoutFilter'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', GET]
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login'; against '/logout'
2018-06-21 23:32:20.647 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', POST]
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /login' doesn't match 'POST /logout
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', PUT]
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /login' doesn't match 'PUT /logout
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /login' doesn't match 'DELETE /logout
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.security.web.FilterChainProxy        : /login at position 5 of 12 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /login' doesn't match 'POST /login
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.security.web.FilterChainProxy        : /login at position 6 of 12 in additional filter chain; firing Filter: 'DefaultLoginPageGeneratingFilter'
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@7db47ef0
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2018-06-21 23:32:20.650 DEBUG 14560 --- [nio-8081-exec-5] o.s.b.w.s.f.OrderedRequestContextFilter  : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@781292c9

**Comment by lor6** [comment]
Hey @sofior No, you aren't doing anything wrong. That endpoint is meant for this article: http://www.baeldung.com/oauth-api-testing-with-spring-mvc 

And the configuration is setup here: https://github.com/Baeldung/spring-security-oauth/blob/master/oauth-authorization-server/src/main/java/org/baeldung/config/OAuth2ResourceServerConfig.java

As you see in the comment, it's only available for the mvc profile. 

I suggest ignoring this one if you aren't specifically interested in the mvc testing. If you want to add new endpoints, it's better to add them in a resource server module.

Cheers.
